INSERT INTO DOAN_TAU (MaDoanTau, TenTau, HangSX, NgVanHanh, LoaiTau) VALUES (N'D001', N'TN1', N'Hyundai Rotem', '2012-05-19', N'T');
INSERT INTO DOAN_TAU (MaDoanTau, TenTau, HangSX, NgVanHanh, LoaiTau) VALUES (N'D002', N'SNT1', N'Siemens', '2009-10-20', N'T');
INSERT INTO DOAN_TAU (MaDoanTau, TenTau, HangSX, NgVanHanh, LoaiTau) VALUES (N'D003', N'TN2', N'Hitachi', '2010-04-13', N'T');
INSERT INTO DOAN_TAU (MaDoanTau, TenTau, HangSX, NgVanHanh, LoaiTau) VALUES (N'D004', N'SE2', N'Kawasaki Heavy Industries', '2011-03-12', N'S');
INSERT INTO DOAN_TAU (MaDoanTau, TenTau, HangSX, NgVanHanh, LoaiTau) VALUES (N'D005', N'TH2', N'Siemens', '2010-01-25', N'T');
INSERT INTO DOAN_TAU (MaDoanTau, TenTau, HangSX, NgVanHanh, LoaiTau) VALUES (N'D006', N'SP3', N'Hyundai Rotem', '2013-09-15', N'S');
INSERT INTO DOAN_TAU (MaDoanTau, TenTau, HangSX, NgVanHanh, LoaiTau) VALUES (N'D007', N'M22', N'Hitachi', '2013-12-07', N'T');
INSERT INTO DOAN_TAU (MaDoanTau, TenTau, HangSX, NgVanHanh, LoaiTau) VALUES (N'D008', N'HP2', N'Bombardier', '2015-02-07', N'T');
INSERT INTO DOAN_TAU (MaDoanTau, TenTau, HangSX, NgVanHanh, LoaiTau) VALUES (N'D009', N'SE4', N'Kawasaki Heavy Industries', '2015-08-18', N'S');
INSERT INTO DOAN_TAU (MaDoanTau, TenTau, HangSX, NgVanHanh, LoaiTau) VALUES (N'D010', N'DN2', N'Alstom', '2015-04-01', N'T');
INSERT INTO DOAN_TAU (MaDoanTau, TenTau, HangSX, NgVanHanh, LoaiTau) VALUES (N'D011', N'DN1', N'Alstom', '2015-03-01', N'T');
INSERT INTO DOAN_TAU (MaDoanTau, TenTau, HangSX, NgVanHanh, LoaiTau) VALUES (N'D012', N'TH1', N'Hyundai Rotem', '2015-02-03', N'T');
INSERT INTO DOAN_TAU (MaDoanTau, TenTau, HangSX, NgVanHanh, LoaiTau) VALUES (N'D013', N'SE8', N'Hitachi', '2010-11-20', N'S');
INSERT INTO DOAN_TAU (MaDoanTau, TenTau, HangSX, NgVanHanh, LoaiTau) VALUES (N'D014', N'SE7', N'Hitachi', '2015-08-13', N'S');
INSERT INTO DOAN_TAU (MaDoanTau, TenTau, HangSX, NgVanHanh, LoaiTau) VALUES (N'D015', N'SP1', N'CRRC', '2010-03-09', N'S');
INSERT INTO DOAN_TAU (MaDoanTau, TenTau, HangSX, NgVanHanh, LoaiTau) VALUES (N'D016', N'NA1', N'Kawasaki Heavy Industries', '2011-07-22', N'T');
INSERT INTO DOAN_TAU (MaDoanTau, TenTau, HangSX, NgVanHanh, LoaiTau) VALUES (N'D017', N'V02', N'Bombardier', '2009-11-24', N'T');
INSERT INTO DOAN_TAU (MaDoanTau, TenTau, HangSX, NgVanHanh, LoaiTau) VALUES (N'D018', N'LP2', N'Hyundai Rotem', '2011-11-17', N'T');
INSERT INTO DOAN_TAU (MaDoanTau, TenTau, HangSX, NgVanHanh, LoaiTau) VALUES (N'D019', N'SP4', N'Hitachi', '2009-05-19', N'S');
INSERT INTO DOAN_TAU (MaDoanTau, TenTau, HangSX, NgVanHanh, LoaiTau) VALUES (N'D020', N'M21', N'CRRC', '2011-10-02', N'T');
INSERT INTO DOAN_TAU (MaDoanTau, TenTau, HangSX, NgVanHanh, LoaiTau) VALUES (N'D021', N'SQN1', N'Siemens', '2012-05-27', N'T');
INSERT INTO DOAN_TAU (MaDoanTau, TenTau, HangSX, NgVanHanh, LoaiTau) VALUES (N'D022', N'V01', N'CRRC', '2010-09-21', N'T');
INSERT INTO DOAN_TAU (MaDoanTau, TenTau, HangSX, NgVanHanh, LoaiTau) VALUES (N'D023', N'HP1', N'CRRC', '2010-10-05', N'T');
INSERT INTO DOAN_TAU (MaDoanTau, TenTau, HangSX, NgVanHanh, LoaiTau) VALUES (N'D024', N'SE1', N'Hitachi', '2012-11-04', N'S');
INSERT INTO DOAN_TAU (MaDoanTau, TenTau, HangSX, NgVanHanh, LoaiTau) VALUES (N'D025', N'NA2', N'Hitachi', '2009-08-09', N'T');
INSERT INTO DOAN_TAU (MaDoanTau, TenTau, HangSX, NgVanHanh, LoaiTau) VALUES (N'D026', N'SNT2', N'Siemens', '2013-12-09', N'T');
INSERT INTO DOAN_TAU (MaDoanTau, TenTau, HangSX, NgVanHanh, LoaiTau) VALUES (N'D027', N'SE3', N'Bombardier', '2012-04-12', N'S');
INSERT INTO DOAN_TAU (MaDoanTau, TenTau, HangSX, NgVanHanh, LoaiTau) VALUES (N'D028', N'SP2', N'Hitachi', '2014-01-03', N'S');
INSERT INTO DOAN_TAU (MaDoanTau, TenTau, HangSX, NgVanHanh, LoaiTau) VALUES (N'D029', N'LP1', N'Siemens', '2012-02-05', N'T');
INSERT INTO DOAN_TAU (MaDoanTau, TenTau, HangSX, NgVanHanh, LoaiTau) VALUES (N'D030', N'SE5', N'CRRC', '2010-07-22', N'S');
