INSERT INTO GA (MaGa, TenGa) VALUES (N'GA001', N'Biên Hòa');
INSERT INTO GA (MaGa, TenGa) VALUES (N'GA002', N'Bình Thuận');
INSERT INTO GA (MaGa, TenGa) VALUES (N'GA003', N'Bắc Giang');
INSERT INTO GA (MaGa, TenGa) VALUES (N'GA004', N'Bỉm Sơn');
INSERT INTO GA (MaGa, TenGa) VALUES (N'GA005', N'Diêu Trì');
INSERT INTO GA (MaGa, TenGa) VALUES (N'GA006', N'Gia Lâm');
INSERT INTO GA (MaGa, TenGa) VALUES (N'GA007', N'Giáp Bát');
INSERT INTO GA (MaGa, TenGa) VALUES (N'GA008', N'Huế');
INSERT INTO GA (MaGa, TenGa) VALUES (N'GA009', N'Hà Nội');
INSERT INTO GA (MaGa, TenGa) VALUES (N'GA010', N'Hạ Long');
INSERT INTO GA (MaGa, TenGa) VALUES (N'GA011', N'Hải Dương');
INSERT INTO GA (MaGa, TenGa) VALUES (N'GA012', N'Hải Phòng');
INSERT INTO GA (MaGa, TenGa) VALUES (N'GA013', N'Kép');
INSERT INTO GA (MaGa, TenGa) VALUES (N'GA014', N'Lào Cai');
INSERT INTO GA (MaGa, TenGa) VALUES (N'GA015', N'Lạng Sơn');
INSERT INTO GA (MaGa, TenGa) VALUES (N'GA016', N'Nam Định');
INSERT INTO GA (MaGa, TenGa) VALUES (N'GA017', N'Nha Trang');
INSERT INTO GA (MaGa, TenGa) VALUES (N'GA018', N'Ninh Bình');
INSERT INTO GA (MaGa, TenGa) VALUES (N'GA019', N'Phú Thọ');
INSERT INTO GA (MaGa, TenGa) VALUES (N'GA020', N'Phủ Lý');
INSERT INTO GA (MaGa, TenGa) VALUES (N'GA021', N'Quy Nhơn');
INSERT INTO GA (MaGa, TenGa) VALUES (N'GA022', N'Quảng Ngãi');
INSERT INTO GA (MaGa, TenGa) VALUES (N'GA023', N'Sài Gòn');
INSERT INTO GA (MaGa, TenGa) VALUES (N'GA024', N'Thanh Hóa');
INSERT INTO GA (MaGa, TenGa) VALUES (N'GA025', N'Tháp Chàm');
INSERT INTO GA (MaGa, TenGa) VALUES (N'GA026', N'Tuy Hòa');
INSERT INTO GA (MaGa, TenGa) VALUES (N'GA027', N'Uông Bí');
INSERT INTO GA (MaGa, TenGa) VALUES (N'GA028', N'Vinh');
INSERT INTO GA (MaGa, TenGa) VALUES (N'GA029', N'Yên Bái');
INSERT INTO GA (MaGa, TenGa) VALUES (N'GA030', N'Yên Viên');
INSERT INTO GA (MaGa, TenGa) VALUES (N'GA031', N'Đà Nẵng');
INSERT INTO GA (MaGa, TenGa) VALUES (N'GA032', N'Đông Hà');
INSERT INTO GA (MaGa, TenGa) VALUES (N'GA033', N'Đồng Hới');
INSERT INTO GA (MaGa, TenGa) VALUES (N'GA034', N'Đồng Đăng');
INSERT INTO GA (MaGa, TenGa) VALUES (N'GA035', N'Phan Thiết');
INSERT INTO GA (MaGa, TenGa) VALUES (N'GA036', N'Thái Nguyên');
INSERT INTO GA (MaGa, TenGa) VALUES (N'GA037', N'Bắc Ninh');
